gd-edit/GDE

GDEdit/GDEdit/Application/Database.cs, GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/GamesaveValues/ObjectParameter.cs, GDEdit/GDEdit/Utilities/Functions/GeometryDash/Gamesave.cs
=> Retarded fixes

GDEdit/GDEdit/Application/Editor/Editor.cs, GDEdit/GDEdit/GDEdit.csproj, GDEdit/GDEdit/Utilities/Attributes/ObjectStringMappableAttribute.cs, GDEdit/GDEdit/Utilities/Objects/General/Point.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObject.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/GeneralObject.cs
Basic editor algorithms and functionality
=> Editor algorithms

GDEdit/GDE.App/Main/Colours/GDEColours.cs, GDEdit/GDE.App/Main/Screens/MainScreen.cs, GDEdit/GDE.App/Main/UI/Tabs/LevelTab.cs
=> LevelTab & Colours

GDEdit/GDEdit/Utilities/Information/GeometryDash/LevelObjectInformation.cs, GDEdit/GDEdit/Utilities/Information/GeometryDash/ObjectLists.cs, GDEdit/GDEdit/Utilities/Information/GeometryDash/PreviousVersions.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasEasing.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasPrimaryBlockID.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasPrimaryItemID.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasSecondaryBlockID.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasSecondaryGroupID.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasTargetColorID.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasTargetGroupID.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Interfaces/IHasTargetItemID.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Trigger.cs
=> Documentation

GDEdit/GDEdit/GDEdit.csproj, GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/SpecialColorID.cs, GDEdit/GDEdit/Utilities/Functions/GeometryDash/ColorTriggerTypes.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/GeneralObject.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/LevelObjectCollection.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/BGColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/Color1ColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/Color2ColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/Color3ColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/Color4ColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/GRND2ColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/GRNDColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/LineColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/ObjColorTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ColorTriggers/ThreeDLColorTrigger.cs
=> Color trigger

GDEdit/GDE.App/Main/GDEApp.cs
This will report any errors any user might experience although there is no notification that it has been reported
=> Raven logger

GDEdit/GDE.App/Main/Colors/GDEColors.cs, GDEdit/GDE.App/Main/Objects/ObjectBase.cs, GDEdit/GDE.App/Main/Panels/Panel.cs, GDEdit/GDE.App/Main/Screens/Edit/Editor.cs, GDEdit/GDE.App/Main/Screens/LevelCreation.cs, GDEdit/GDE.App/Main/Screens/MainScreen.cs, GDEdit/GDE.App/Main/Toasts/ToastNotification.cs, GDEdit/GDE.App/Main/UI/Tabs/LevelTab.cs, GDEdit/GDE.App/Main/UI/Toolbar/ToolbarMenu.cs, GDEdit/GDE.Tests/Visual/TestCaseObject.cs
This fixes various things across the project, quality of life things that **must** be taken into account as soon as the code is written.
=> Fix various things

GDEdit/GDEdit/Application/Editor/Editor.cs, GDEdit/GDEdit/GDEdit.csproj, GDEdit/GDEdit/Utilities/Information/GeometryDash/Speeds.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/GuidelineCollection.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/SpeedSegment.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/SpeedSegmentCollection.cs
Untested; theoretically correct I guess?
=> Add functions to snap triggers to guidelines

GDEdit/GDEdit/Application/Database.cs, GDEdit/GDEdit/GDEdit.csproj, GDEdit/GDEdit/Utilities/Objects/GeometryDash/CustomLevelObjectCollection.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/FolderNameCollection.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelCollection.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/SongMetadataCollection.cs
Improves the database in a lot of things; still requires a few little things but for the most part it's good. Still untested, therefore not 100% working.
=> Database improvements

GDEdit/GDEdit/GDEdit.csproj, GDEdit/GDEdit/Utilities/Functions/GeometryDash/LevelLengthConversion.cs, GDEdit/GDEdit/Utilities/Information/GeometryDash/LevelLengths.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs
Minor improvements to the length of a level
=> Level length

GDEdit/GDEdit/Utilities/Objects/General/BitArray8.cs
Improves things on the `BitArray8` struct.
=> BitArray8 fix

GDEdit/GDE.Tests/Visual/TestCaseEditor.cs
=> Fix editor test case

GDEdit/GDEdit/GDEdit.csproj, GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/ObjectParameter.cs, GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/TriggerType.cs, GDEdit/GDEdit/Utilities/Objects/General/BitArray16.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/GeneralObject.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/ScaleTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/Trigger.cs
The game is starting to feel really expertized all of a sudden.
=> Add information from the latest sneak peek video

GDEdit/GDEdit/Application/Editor/Editor.cs, GDEdit/GDEdit/Utilities/Functions/Extensions/GenericArrayExtensions.cs, GDEdit/GDEdit/Utilities/Objects/General/Color.cs, GDEdit/GDEdit/Utilities/Objects/General/Point.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/ColorChannels/ColorChannel.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/General/HSVDifference.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/GeneralObject.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/LevelObjectCollection.cs
Some events are not added yet; this will be most likely reworked in a class form
=> Implement undo/redo

CodeStyle.md, README.md
This adds more infromation about the project and its code
=> Update project info

GDEdit/GDEdit/GDEdit.csproj, GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/ObjectParameter.cs, GDEdit/GDEdit/Utilities/Information/GeometryDash/LevelObjectInformation.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/OrbPad.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Orbs/Orb.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Orbs/TriggerOrb.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/SpecialObjects/Pads/Pad.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/CameraOffsetTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/MoveTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/RandomTrigger.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/StaticCameraTrigger.cs
P.S. Nice branch name I guess?
=> Sneak peek future-proofing v201905250312+3:00

GDEdit/GDEdit/Utilities/Enumerations/GeometryDash/ObjectParameter.cs, GDEdit/GDEdit/Utilities/Information/GeometryDash/LevelObjectInformation.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/Level.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/SongMetadata.cs
Fixes crashes on frequent enough occasions.
=> General level loading fixes

GDEdit/GDE.App/Main/Screens/Edit/Components/IDMigrationStepList.cs, GDEdit/GDEdit/Utilities/Objects/GeometryDash/LevelObjects/Triggers/PulseTrigger.cs
=> Shut the fuck up

GDEdit/GDE.App/Main/Containers/KeyBindingContainers/IDMigrationActionContainer.cs, GDEdit/GDE.App/Main/Screens/Edit/Components/IDMigrationStepList.cs, GDEdit/GDEdit/Application/Editor/Editor.cs
This adds some stuff right before releasing that were noticed the last moment.
=> Quick implementations

FeaturesToBeAdded.md, README.md
Better README, more legal, more user-friendly stuff. +100 marketing points.
=> Improve project info (yet again)

GDEdit/GDE.App/Main/UI/BreadcrumbNavigation.cs
=> Fix breadcrumb

GDEdit/GDEdit/Utilities/Information/GeometryDash/Speeds.cs
More information about the speed constants was given by Cos8o, another good steps towards making this API more useful.
=> Speed constants

GDEdit/GDE.App/Main/Levels/GridOrigin.cs, GDEdit/GDE.App/Main/Screens/Edit/Components/Camera.cs, GDEdit/GDE.App/Main/Screens/Edit/EditorScreen.cs
I've added the origin axes in the editor.
(And i don't know why but i struggled with git in VS lmao)
=> Add origin axes in editor
